pipeline:
  build:
    image: pypy:2
    commands:
      - make pypy-c
  package:
    image: pypy:2
    commands:
      - pypy pypy/tool/release/package.py --archive-name mesapy --targetdir . --without-cffi
