kind: pipeline
name: sgx_minimal

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init
  - git checkout -b temp-branch-name # make a temp branch name to work around a issue in building process

- name: build-minimal
  image: mesapy/build-mesapy:sgx
  pull: always
  commands:
  - make sgx_minimal

---

kind: pipeline
name: sgx

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init
  - git checkout -b temp-branch-name # make a temp branch name to work around a issue in building process

- name: build
  image: mesapy/build-mesapy:sgx
  pull: always
  commands:
  - make sgx
