kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init

- name: build
  image: mesalocklinux/build-mesalock-linux
  pull: always
  commands:
  - git checkout -b temp-branch-name # make a temp branch name to work around a issue in building process
  - export PYPY_USESSION_DIR=$(pwd)/pypy-usession-dir
  - mkdir pypy-usession-dir
  - make pypy-c

- name: package
  image: mesalocklinux/build-mesalock-linux
  commands:
  - export PYPY_USESSION_DIR=$(pwd)/pypy-usession-dir
  - pypy pypy/tool/release/package.py --archive-name mesapy --targetdir . --without-cffi

- name: deploy
  image: mesalocklinux/build-mesalock-linux
  commands:
  - apt-get update
  - apt-get install -q -y sshpass
  - sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no mesapy.tar.bz2 "$USERNAME"@"$HOSTNAME":"$TARGET_PATH"/"$DRONE_COMMIT_SHA"-mesapy.tar.bz2
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
    HOSTNAME:
      from_secret: hostname
    TARGET_PATH:
      from_secret: target_path
  when:
    event:
    - push
    branch:
    - master

node:
  instance: sgx
