pipeline:
  build:
    image: mesalocklinux/build-mesalock-linux
    pull: true
    commands:
      - make pypy-c
  package:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - pypy pypy/tool/release/package.py --archive-name mesapy --targetdir . --without-cffi
