kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init

- name: build-minimal
  image: mesalocklinux/build-mesalock-linux
  pull: always
  commands:
  - apt-get update && apt-get install -q -y libltdl-dev texinfo
  - git checkout -b temp-branch-name # make a temp branch name to work around a issue in building process
  - export PYPY_USESSION_DIR=$(pwd)/pypy-usession-dir
  - mkdir pypy-usession-dir
  - make sgx_minimal

- name: build
  image: mesalocklinux/build-mesalock-linux
  pull: always
  commands:
  - apt-get update && apt-get install -q -y libltdl-dev texinfo
  - make sgx
